#!/bin/bash

# This file will back up any given file by forst creating an initial backup if the given file is not present. Then it will backup only the differences as the filename + linux time.

#########################################
# Use text file with the following format
#
#source_dir=~/
#dest_dir=/tmp
#backup_name=backup
#
##########################################
function assign_backup_detail()
{
while read line ;do export $line;done < input.props 

}
function make_continous_backup()
{
     incremental_file=$backup_name`date +%s`.tar     
     
     if [ -f $dest_dir/$backup_name.tar ]
     then
	tar cvf $dest_dir/$incremental_file.tar ~/ -g $dest_dir/$backup_name.snar
        exit
     else
	tar cvf $dest_dir/$backup_name.tar ~/ -g $dest_dir/$backup_name.snar
	exit
     fi
}

assign_backup_detail
make_continous_backup

